### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by adamrenklint** [adamrenklint/prost#1]
The current error messages are clearly an improvement over vanilla spec, but they still leave some things to be desired.

```
/Users/adamrenklint/Projects/trn.gl/target/boot_test_cljs.runner.out/prost/core.cljs:74
      (throw (js/TypeError (arg-err-str fs f vs v)))))
             ^
TypeError: invalid argument 'x', expected 12 to be set?
    at prost$core$arg_STAR_ (/Users/adamrenklint/Projects/trn.gl/target/boot_test_cljs.runner.out/prost/core.cljs:74:14)
    at trngl$core$foobar (/Users/adamrenklint/Projects/trn.gl/target/boot_test_cljs.runner.out/trngl/core.cljs:13:10)
    at Object.<anonymous> (/Users/adamrenklint/Projects/trn.gl/target/boot_test_cljs.runner.out/trngl/core.cljs:16:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

- The first line in the stack trace is not necessary, could be trimmed
- Or move the `line:col` to the error message itself:
```
TypeError: invalid argument 'x', expected 12 to be set? in trngl.core/foobar
(/Users/adamrenklint/Projects/trn.gl/target/boot_test_cljs.runner.out/trngl/core.cljs:13:10)
```

**Comment by adamrenklint** [comment]
Improved error messages https://github.com/adamrenklint/prost/commit/1cd9004bdca8cfcc97248396fb78a22ba211ade5
